config/routes.rb
Rails.application.routes.draw do

    get "/cities/:id", to: "states#show"
    get "/cities/:city_id/categories", to: "cities#show"

  resources :cities , path: "cities" do

    resources :categories , path: "categories"

  end

  post "/company/find", to: "companies#search", as: "companies_search"
  get "/company/find/:query/:query_city", to: "companies#search_results", as: "companies_search_results"

  root "states#index"

  resources :companies, path: "companies"

  resources "contacts", only: [:new, :create]
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :state
  has_many :companies
  has_and_belongs_to_many :cities


  extend FriendlyId
    friendly_id :name, use: :slugged

  def keyword_name(city)
    "#{name}, #{city.name}, #{city.state.name}, #{city.state.abbreviation}"
  end

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  has_many :companies
  has_and_belongs_to_many :categories


  extend FriendlyId
    friendly_id :name, use: :slugged

  def full_name
    "Company addresses and phone numbers in #{name}, #{state.abbreviation}"
  end

  def keyword_name
    "#{name}, #{state.name}, #{state.abbreviation}"
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :state
  belongs_to :city
  belongs_to :category


  extend FriendlyId
    friendly_id :full_name, use: :slugged
    validates :name, presence: true
    validates :company_external_id, uniqueness: true


  def capitalize_name
    "#{name.mb_chars.capitalize.to_s}"
  end

  def full_name
    "#{capitalize_name} - #{city.name}, #{state.abbreviation}"
  end

  def keyword_name
    "#{capitalize_name}, #{city.name}, #{state.name}, #{state.abbreviation}, #{category.name}"
  end

  def category_company
    near_company = Company.where(category: category, city: city)

    number_of_companies = 10

    number = near_company.count

    empresas = []
    if number >= number_of_companies
      empresas += near_company.includes(:category, :city, :state).order(random).limit(number_of_companies)
    elsif number != 0
      empresas += near_company.includes(:category, :city, :state).order(random).limit(number)
      empresas += Company.where(city: city).includes(:category, :city, :state).order(random).limit(number_of_companies - number)
    else
      empresas += Company.where(city: city).includes(:category, :city, :state).order(random).limit(number)
    end

    empresas
  end

  def self.search(query_param, city_param)
    if query_param.present? && city_param.present?
      city = City.where("name LIKE ?", "#{city_param}%").limit(1).first

      where("name LIKE :query AND city_id = :city_id", {query: "%#{query_param}%", city_id: city.id})
    elsif query_param.present?

    elsif city_param.present?

    else
      nil
    end
  end

private
  def random
    adapter = ActiveRecord::Base.connection.adapter_name #not sure what the real output would be here, test it.
    if adapter == "SQLite"
      "RANDOM()"
    else
      "RAND()"
    end
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :cities
  has_many :categories


  extend FriendlyId

  friendly_id :slug_formula, use: :slugged
   validates :abbreviation, uniqueness: true
  def slug_formula
    "#{name} #{abbreviation}"
  end

  def keyword_name
    "#{name}, #{abbreviation}"
  end

  def full_name
    "Company addresses and phone numbers in #{name}"
  end

  def name
    map = {
      "AAT" => "Australian Antarctic Territory",
      "ACT" => "Australian Capital Territory",
      "HIMI" => "Heard Island and McDonald Islands",
      "JBT" => "Jervis Bay Territory",
      "NSW" => "New South Wales",
      "NT" => "Northern Territory",
      "QLD" => "Queensland",
      "SA" => "South Australia",
      "TAS" => "Tasmania",
      "VIC" => "Victoria",
      "WA" => "Western Australia"
    }

    map[abbreviation]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @city = City.find_by(slug: params[:city_id])
    @category = Category.find_by(slug: params[:id])
    @companies = Company.where(category: @category, city: @city).order(:slug).page (params[:page])
    @category_full_name = "#{@category.name} company addresses and phone numbers in #{@city.name}, #{@city.state.abbreviation}"
  end


end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
 def index
  @cities = City.all
  end

  def show
    @city = City.find_by(slug: params[:city_id])
    @categories = @city.categories.order(:slug).page(params[:page])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.friendly.find(params[:id])
  end

  def search
    return redirect_to root_path if params[:query].blank? && params[:query_city].blank?
    redirect_to companies_search_results_path(params[:query], params[:query_city])
  end

  def search_results
    @companies = Company.search(params[:query], params[:query_city]).order(:slug).page(params[:page])
end

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def index
    @states = State.all.order(:slug)
  end
  def show
    @state = State.find_by(slug: params[:id])
    @cities = City.where(state: @state).order(:slug).page(params[:page])

    if !@state
      render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title, homepage = nil)
    if homepage
      title_string = page_title
    else
      title_string = "#{page_title} - au.Searchalia.com"
    end

    content_for(:title, title_string)
  end

  def keyword_names(page_keyword, homepage = nil)
    if homepage
      keyword_string = page_keyword
    else
      keyword_string = "#{page_keyword}, Australia, search, telephone, address, search address and telephones,business directory, searchalia.com.au"
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/categories/show.html.erb
<%= title(@category_full_name)%>
<% content_for(:metadescription) do %>
  <meta name="description" content="<%= "Phone and address for #{@category.name} bussiness in #{@city.name}"%>">
  <meta name="keywords" content = "<%= keyword_names(@category.keyword_name(@city))%>">
  <% content_for :canonical do %>
  <link rel="canonical" href="<%=city_category_url(@city,@category)%>">
<% end %>
  <% end %>
<div class="row site">
  <div class="listing col-md-12">
    <h1><%= @category.name %> companies in <%= link_to(@city.name, city_categories_path(@city, @categories))%></h1>
    <ul class="lists clearfix">
      <% @companies.each do |company| %>
      <li class="col-xs-4 col-sm-4">
        <span><%= link_to company.capitalize_name, company_path(company), title: "#{company.name} company in #{company.city.name}" %></span>
       </li>
      <%end%>
    </ul>
    <div class="text-center">
      <ul class="pagination">
        <%= paginate @companies %>
      </ul>
    </div>
  </div>
</div>

app/views/cities/show.html.erb
<% title(@city.full_name) %>
<% content_for(:metadescription) do %>
  <meta name="description" content="<%= "Phone and address for bussinesses in #{@city.name}, #{@city.state.name}" %>">
  <meta name="keywords" content = "<%= keyword_names(@city.keyword_name)%>">
<% end %>
<% content_for(:canonical) do %>
  <link rel ="canonical" href="<%=city_categories_url(@city)%>">
<%end%>
<div class="row site">
  <div class="listing col-md-12">
    <h1> Categories in <%= @city.name %>, <%= link_to(@city.state.name, city_path(@city.state)) %></h1>
    <ul class="lists clearfix">
      <% @categories.each do |category| %>
        <li class="col-xs-4 col-sm-4">
          <span><%= link_to category.name, city_category_path(@city,category), title: "#{category.name} businesses in #{@city.name}, #{@city.state.name}" %></span>
        </li>
      <%end%>
    </ul>
    <div class="text-center">
        <%= paginate @categories %>
    </div>
  </div>
</div>

app/views/companies/search_results.html.erb
<%= title "#{@companies.count} businesses for #{params[:query]} - #{params[:query_city]}"%>
<% content_for(:metadescription) do %>
  <meta name="description" content="<%= "#{@companies.count} companhias do #{params[:query]} em #{params[:query_city]}"%>">
  <% end %>
<div class="row site">
  <div class="listing col-sm-8 col-md-12">
    <h1><%=@companies.count%> businesses for <%= params[:query]%> in <%= params[:query_city]%></h1>
      <ul class="lists clearfix">
        <% @companies.each do |company| %>
          <li class="col-xs-4 col-sm-4">
            <span><%= link_to(company.name.capitalize, company_path(company)) %></span>
            <%= company.category.name %>,
            <%= company.city.name %>
          </li>
        <% end %>
      </ul>
        <div class="text-center">
         <%= paginate @companies %>
        </div>

  </div>
</div>

app/views/companies/show.html.erb
<% title(@company.full_name) %>
<% content_for(:metadescription) do %>
  <meta name="description" content="<%= "Phone and address, #{@company.full_name}" %>">
  <meta name="keywords" content = "<%= keyword_names(@company.keyword_name)%>">
<% end %>
<% content_for(:canonical) do %>
  <link rel ="canonical" href="<%= company_url(@company)%>">
<%end%>
<div class="row sitecompany">
  <div class="adgoogle">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      <!-- Searchalia Top Ad -->
      <ins class="adsbygoogle"
           style="display:block"
           data-ad-client="ca-pub-1633713562816559"
           data-ad-slot="6839827225"
           data-ad-format="auto"></ins>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
  </div>
  <ol class="breadcrumb">
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
      <a href="<%= root_url %>" itemprop="url" title="Searchalia">
        <span itemprop="title">Searchalia</span>
      </a>
    </li>
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
      <a href="<%= city_path(@company.state) %>" itemprop="url" title="<%= @company.state.name + '-' + @company.state.name %>">
        <span itemprop="title"><%= @company.state.name %></span>
      </a>
    </li>
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
      <a href="<%= city_categories_path(@company.city) %>" itemprop="url" title="<%= @company.city.name %>">
        <span itemprop="title"><%= @company.city.name %></span>
      </a>
    </li>
    <li itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
      <a href="<%= city_category_path(@company.city, @company.category) %>" itemprop="url" title="<%= @company.category.name %>">
        <span itemprop="title"><%= @company.category.name %></span>
      </a>
    </li>
    <li class="active" itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
      <span itemprop="title"><%= @company.capitalize_name %></span>
    </li>
  </ol>
  <div class="company col-md-8">
    <div class="row companymain">
      <div class="companyinfo" itemscope itemtype="http://schema.org/LocalBusiness">
        <h1 itemprop="name"><%= @company.name %></h1>
        <div class="category">
          <span class="bigwords">Category </span></br>
          <%= link_to(@company.category.name, city_category_path(@company.city, @company.category)) %>
        </div>
        <div class="Endereço" itemscope itemtype="http://schema.org/PostalAddress">
          <span class="bigwords">Address</span></br>
          <% if @company.address %>
            <span itemprop="address"><%= @company.address %>, </span>
          <% end%>
          <span itemprop="addressLocality"><%= @company.city.name %>,</span>
          <span itemprop="addressRegion"><%= @company.state.name%>,</span>
          <span itemprop="postalCode"><%= @company.postal_code %></span>
        </div>
        <% if @company.telephone?%>
          <div class="telefone" itemprop="telephone">
            <div class="telephoneimg">
              <%= image_tag("telephone.png", :alt => "Telephone")%>
            </div>
            <span class="bigwords">Telephone</span>
            <p><%= @company.telephone %></p>
          </div>
        <% end %>
      </div>
      <div class="ad col-sm">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
          <!-- Searchalia Bottom Ad -->
          <ins class="adsbygoogle"
               style="display:block"
               data-ad-client="ca-pub-1633713562816559"
               data-ad-slot="2409627626"
               data-ad-format="auto"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      </div>
    </div>
  </div>
  <aside class="aside list-group col-xs-12 col-sm-8 col-md-4">
    <h3 class="list-group-heading nearcompanies"> Near companies from <%= @company.name %>: </h3>
    <ul>
      <li class="ad-aside">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- Aside Ad -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-1633713562816559"
             data-ad-slot="3287366422"
             data-ad-format="rectangle"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      </li>
      <% @company.category_company.each do |company| %>
        <% if company == @company %>
        <% else %>
          <li class="list-group-item">
            <p class="list-group-item-heading"><%= link_to(company.capitalize_name, company_path(company)) %></p>
            <p class="list-group-item-text"><%= company.category.name %>,
            <%= company.city.name %> - <%= company.state.name %></p>
          </li>
        <% end %>
      <% end %>
    </ul>
  </aside>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class ="navbar-inner">
    <ul>
 Companies in other countries:
  <li><%= link_to "Brasil","http://www.brasilist.com.br", {:title => "Company address and telephones in Brasil"} %></li>
  <li><%= link_to "Portugal","http://www.searchalia.pt", {:title => "Company address and telephones in Portugal"} %></li>
  </ul>
    <div class = "container footer-margin-top">
      <p> ©au.searchalia.com <%= Time.now.year %> - Business directory </p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="row logo">
  <span class="col-md-3"><%= link_to "Searchalia", root_path %></span>
  <%= form_tag companies_search_path, :class => "form-inline" do %>
    <%= text_field_tag :query, params[:query] , placeholder: "Company", :class=>"form-control col-md-2"  %>
    <%= text_field_tag :query_city, params[:query_city] , placeholder: "City" , :class=>"form-control col-md-2"%>
    <%= submit_tag "Find" , type: 'submit', class: "btn btn-primary col-md-2",  :name => nil %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= yield :title %></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <%= yield :metadescription %>
    <%= yield :canonical %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= csrf_meta_tags %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-60179512-5', 'auto');
      ga('send', 'pageview');
    </script>

  </head>
  <body>
    <div class="container">
      <%if current_page?(root_path)%>
        <% else %>
      <%= render 'layouts/header' %>
      <% end %>
      <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/states/index.html.erb
<% title("Searchalia - Australian Company addresses and phone numbers", true) %>
<% content_for(:metadescription) do %>
  <meta name="description" content="<%= "Australian business directory. Search for businesses address and telephones"%>">
<% end %>
<% content_for :canonical do %>
  <link rel="canonical" href="<%= root_url %>">
<% end %>
<div class="row site">
  <div class="mainpage col-md-8">
    <div class="row mainlogo">
        <span class="logotitle col-md-5"><%= link_to "Searchalia", root_path%></span>
        <span class="pagetitle col-md-6"><h1> Find more than <%= number_with_delimiter(Company.count, delimiter: '.') %> local businesses in Australia  </h1></span>
    </div>
    <div class="row search">
      <%= form_tag companies_search_path, :class => "form-inline" do %>
        <%= text_field_tag :query, params[:query] , placeholder: "Company", :class=>"form-control"  %>
        <%= text_field_tag :query_city, params[:query_city] , placeholder: "City" , :class=>"form-control"%>
        <%= submit_tag "Find" , type: "submit", class: "btn btn-primary", :name => nil  %>
      <% end %>
    </div>
  </div>
  <div class="listing col-md-8">
    <p>Companies sorted by state:</p>
    <ul class="lists">
      <% @states.each do |state| %>
        <li class="col-xs-4 col-sm-4"> <span><%= link_to state.name, city_path(state), title: "Cidades en #{state.name}" %> </span></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/states/show.html.erb
<% title(@state.full_name) %>
<% content_for(:metadescription) do %>
  <meta name="description" content="<%= "Phone and address for bussinesses in #{@state.name}"%>">
  <meta name="keywords" content = "<%= keyword_names(@state.keyword_name)%>">
<% end %>
<% content_for :canonical do %>
  <link rel="canonical" href="<%=city_url(@state)%>">
<% end %>
<div class="row site">
  <div class="listing col-sm-8 col-md-12">
    <h1>Cities in <%= @state.name %>, <%= link_to "Australia", root_path %></h1>
    <ul class="lists clearfix">
      <% @cities.each do |city| %>
        <li class="col-xs-4 col-sm-4">
          <span><%= link_to city.name, city_categories_path(city), title: "Bussinesses sorted by categories in #{city.name}" %></span>
        </li>
      <% end %>
    </ul>
    <div class="text-center">
        <%= paginate @cities %>
    </div>
  </div>
</div>